### ISSUE TITLE
welcome

### ISSUE THREAD

**Issue by billygl** [JaramilloCris/lolocar-prueba#1]
una pantalla que diga 
“Welcome to Lolocar” y debajo la fecha y hora que se actualiza segundo a segundo.
Además considerar una caja de texto que cuando se ingresa un nombre mayor a 3 caracteres muestra el mensaje:
Hola, [nombre]. Tu nombre tiene [edad] años.
La edad se obtiene del servicio web https://api.agify.io/?name=lolocar donde lolocar es el nombre ingresado y la edad no puede mostrarse como null

**Comment by JaramilloCris** [comment]
15 - 20 minutos
